name: LIFEntrepreneurs
favicon: null
layout_spectrum: 0.12529608560726047
typography_spectrum: 0.24103277665562928
title: Leadership Institute For Entrepreneurs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffedc5'
    - '#060000'
    - '#7e2600'
    - '#467b00'
    - '#7db970'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.9383331029675901
purpose: []
